# Generated by Django 2.0.2 on 2018-02-21 15:48

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='media/songs/', validators=[music.models.validate_audio]),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(default='3:20'),
        ),
    ]
