# Generated by Django 2.0.2 on 2018-02-22 18:10

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_song_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='music/static/album_logo/', validators=[music.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='music/static//songs/', validators=[music.models.validate_audio]),
        ),
    ]
