# Generated by Django 2.0.2 on 2018-02-22 20:36

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20180223_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='', validators=[music.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='', validators=[music.models.validate_audio]),
        ),
    ]
