# Generated by Django 2.0.2 on 2018-02-22 20:43

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20180223_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='static/img/album_logo/', validators=[music.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='static/media/songs/', validators=[music.models.validate_audio]),
        ),
    ]
