# Generated by Django 2.0.2 on 2018-02-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20180224_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='User',
        ),
    ]
