# Generated by Django 2.0.2 on 2018-02-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20180224_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Fisrt-name', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Last-name', max_length=100),
        ),
    ]
