# Generated by Django 2.0.2 on 2018-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_auto_20180224_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('Gurgaon', 'Gurgaon'), ('Delhi', 'Delhi')], default='Gurgaon', max_length=20),
        ),
    ]
