# Generated by Django 2.0.2 on 2018-02-24 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0025_auto_20180224_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Profile',
        ),
    ]
