# Generated by Django 2.0.2 on 2018-02-25 05:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0027_usersong'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersong',
            unique_together={('user', 'song')},
        ),
    ]
