# Generated by Django 2.0.2 on 2018-02-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_auto_20180225_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('LA', 'LA'), ('Boston', 'Boston')], default='LA', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('America', 'America')], default='India', max_length=20),
        ),
    ]
