# Generated by Django 2.0.2 on 2018-02-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_auto_20180225_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('none', 'none'), ('none', 'none')], default='sdfd', max_length=20),
        ),
    ]
