# Generated by Django 2.0.2 on 2018-02-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_auto_20180225_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('Boston', 'Boston'), ('Gurgaon', 'Gurgaon'), ('Delhi', 'Delhi'), ('LA', 'LA'), ('NewYork', 'NewYork')], default='Gurgaon', max_length=20),
        ),
    ]
