# Generated by Django 2.0.2 on 2018-02-25 06:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0031_auto_20180225_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSong',
            new_name='UserSongRelationship',
        ),
    ]
