# Generated by Django 2.0.2 on 2018-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_auto_20180227_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
