# Generated by Django 2.0.2 on 2018-02-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactMe',
        ),
    ]
