# Generated by Django 2.0.2 on 2018-02-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0035_auto_20180227_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMe',
            new_name='Contact',
        ),
    ]
