# Generated by Django 2.0.2 on 2018-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0036_auto_20180227_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='gurgaon', max_length=20),
        ),
    ]
