# Generated by Django 2.0.2 on 2018-03-01 15:32

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0037_auto_20180228_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='static/album_logo/', validators=[music.models.validate_image], verbose_name=models.CharField(max_length=500, unique=True)),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
