# Generated by Django 2.0.2 on 2018-03-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0038_auto_20180301_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default='2000-1-1'),
        ),
    ]
