# Generated by Django 2.0.2 on 2018-03-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0039_auto_20180328_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default='2012-12-12'),
        ),
    ]
