# Generated by Django 2.0.2 on 2018-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0040_auto_20180328_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Bollywood', 'Bollywood'), ('Dance', 'Dance'), ('English', 'English'), ('Hindi', 'Hindi'), ('Hip-Hop', 'Hip-Hop'), ('Love', 'Love'), ('Pop', 'Pop'), ('Punjabi', 'Punjabi'), ('Remix', 'Remix'), ('Rock', 'Rock'), ('Soundtrack', 'Soundtrack')], default='Bollywood', max_length=20),
        ),
    ]
